module.exports = [
  {
    rating: 94,
    brand: 'JBC Coffee Roasters',
    bean: 'ASOPCAFA Colombia',
    reviewDate: 'Dec 2015',
    price: '$14.85/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/asopcafa-colombia/',
    location: 'Madison, Wisconsin',
    origin: 'Huila Department, southern Colombia',
    roast: 'Medium-Light',
    agtron: '60/77',
    aroma: '9',
    body: '8',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/jbclogo_200x200_72dpi1-150x150.jpg',
  },
  {
    rating: 95,
    brand: 'Turning Point Coffee',
    bean: 'Guatemala San Sebastian Natural',
    reviewDate: 'Dec 2015',
    price: '$14.50/250 grams',
    brandUrl: 'http://www.turningpointcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/guatemala-san-sebastian-natural/',
    location: 'San Francisco, California',
    origin: 'Antigua Valley, Guatemala',
    roast: 'Medium-Light',
    agtron: '59/78',
    aroma: '9',
    body: '9',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Turning Point Coffee',
    bean: 'Ethiopia Hachira Natural Espresso',
    reviewDate: 'Dec 2015',
    price: '$22.50/250 grams',
    brandUrl: 'http://www.turningpointcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/ethiopia-hachira-natural-espresso/',
    location: 'San Francisco, California',
    origin: 'Yirgacheffe growing region, southern Ethiopia',
    roast: 'Light',
    agtron: '62/87',
    aroma: '9',
    body: '0',
    withMilk: '9',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Turning Point Coffee',
    bean: 'Ethiopia Kochere Espresso Profile',
    reviewDate: 'Dec 2015',
    price: '$18.00/320 grams',
    brandUrl: 'http://www.turningpointcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/ethiopia-kochere-espresso-profile/',
    location: 'San Francisco, California',
    origin: 'Yirgacheffe growing region, southern Ethiopia',
    roast: 'Medium-Light',
    agtron: '50/79',
    aroma: '9',
    body: '0',
    withMilk: '9',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Victrola Coffee Roasters',
    bean: 'Kenya Nyeri Kiama FCS Ichuga Factory Peaberry',
    reviewDate: 'Dec 2015',
    price: '$19.50/12 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/kenya-nyeri-kiama-fcs-ichuga-factory-peaberry/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Turnstile Coffee Roasters',
    bean: 'Kenya Nyeri Thageini',
    reviewDate: 'Dec 2015',
    price: '$18.00/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/kenya-nyeri-thageini/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 95,
    brand: "Simon Hsieh's Aroma Roast Coffees",
    bean: 'Kenya AA Lot-125 “Queen Flora”',
    reviewDate: 'Dec 2015',
    price: 'NT $900/8 ounces',
    beanUrl: 'http://www.coffeereview.com/review/kenya-aa-lot-125-queen-flora/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 94,
    brand: "Simon Hsieh's Aroma Roast Coffees",
    bean: 'Ethiopia Natural Yirgacheffe Phoenix Special “King Solomon”',
    reviewDate: 'Dec 2015',
    price: 'NT $800/8 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/ethiopia-natural-yirgacheffe-phoenix-special-king-solomon/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 94,
    brand: "Simon Hsieh's Aroma Roast Coffees",
    bean: 'Fully Washed Ethiopia Phoenix Special “Dr. Evil”',
    reviewDate: 'Dec 2015',
    price: 'NT $700/8 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/fully-washed-ethiopia-phoenix-special-dr-evil/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: "Simon Hsieh's Aroma Roast Coffees",
    bean: 'Sulawesi “Tanah Kebangkitan” Phoenix Special Espresso',
    reviewDate: 'Dec 2015',
    price: 'NT $700/8 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/sulawesi-tanah-kebangkitan-phoenix-special-espresso/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: "Simon Hsieh's Aroma Roast Coffees",
    bean: 'Kenya AA Lot-122 “Excalibur” Espresso',
    reviewDate: 'Dec 2015',
    price: 'NT $900/8 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/kenya-aa-lot-122-excalibur-espresso/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Old Soul Co.',
    bean: 'Panama Elida Natural Lot #13',
    reviewDate: 'Dec 2015',
    price: '$20.00/250 grams',
    beanUrl: 'http://www.coffeereview.com/review/panama-elida-natural-lot-13/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Dragonfly Coffee Roasters',
    bean: 'Emma’s Jo: The Leam Hammer Competition Espresso',
    reviewDate: 'Dec 2015',
    price: '$18.00/12 ounces',
    brandUrl: 'http://www.dragonflycoffeeroasters.com',
    beanUrl:
      'http://www.coffeereview.com/review/emmas-jo-the-leam-hammer-competition-espresso/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Old Soul Co.',
    bean: 'Costa Rica Sumava Natural Lot',
    reviewDate: 'Dec 2015',
    price: '$20.00/250 grams',
    beanUrl:
      'http://www.coffeereview.com/review/costa-rica-sumava-natural-lot/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 96,
    brand: "PT's Coffee Roasting Co.",
    bean: 'Panama Auromar Geisha Natural Peaberry',
    reviewDate: 'Dec 2015',
    price: '$40.00/8 ounces',
    brandUrl: 'http://www.ptscoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/panama-auromar-geisha-natural-peaberry/',
    location: 'Topeka, Kansas',
    origin: 'Boquete growing region, western Panama',
    roast: 'Medium-Light',
    agtron: '53/70',
    aroma: '9',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/12/11_375x375-150x150.jpg',
  },
  {
    rating: 95,
    brand: 'Geisha Coffee Roaster',
    bean: 'El Burro Geisha Tachi Natural',
    reviewDate: 'Dec 2015',
    price: '$46.95/12 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/el-burro-geisha-tachi-natural/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Ghost Town Coffee Roasters',
    bean: 'Holiday Blend',
    reviewDate: 'Dec 2015',
    price: '$15.25/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/holiday-blend-23/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/12/24_375x375-150x150.jpg',
  },
  {
    rating: 95,
    brand: 'Lab 146',
    bean: 'Holiday Blend',
    reviewDate: 'Dec 2015',
    price: '$25.00/8 ounces',
    beanUrl: 'http://www.coffeereview.com/review/holiday-blend-22/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Old Soul Co.',
    bean: 'Nicaragua Pacamara Los Congos Lot #8',
    reviewDate: 'Dec 2015',
    price: '$20.00/250 grams',
    beanUrl:
      'http://www.coffeereview.com/review/nicaragua-pacamara-los-congos-lot-8/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/12/19_375x375-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'Giv COFFEE',
    bean: 'Panama Boquete Kotowa Gesha Natural',
    reviewDate: 'Dec 2015',
    price: '$45.00/8 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/panama-boquete-kotowa-gesha-natural/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Olympia Coffee Roasting',
    bean: 'Holiday Blend',
    reviewDate: 'Dec 2015',
    price: '$18.90/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/holiday-blend-21/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: "Willoughby's Coffee & Tea",
    bean: 'Panama Finca Auromar Camilina Natural',
    reviewDate: 'Dec 2015',
    price: '$50.00/8 ounces',
    brandUrl: 'http://www.willoughbyscoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/panama-finca-auromar-camilina-natural/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: 'JBC Coffee Roasters',
    bean: 'El Aguila SL-28 El Salvador',
    reviewDate: 'Nov 2015',
    price: '$18.75/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/el-aguila-sl-28-el-salvador/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Dragonfly Coffee Roasters',
    bean: 'Ethiopia Sidama Special Lot Natural',
    reviewDate: 'Nov 2015',
    price: '$18.00/12 ounces',
    brandUrl: 'http://www.dragonflycoffeeroasters.com',
    beanUrl:
      'http://www.coffeereview.com/review/ethiopia-sidama-special-lot-natural/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Temple Coffee and Tea',
    bean: 'Panama Finca Deborah Caturra Natural',
    reviewDate: 'Nov 2015',
    price: '$20.00/8 ounces',
    brandUrl: 'http://www.templecoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/panama-finca-deborah-caturra-natural/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 96,
    brand: 'AHRIRE Roasting',
    bean: 'Nekisse Red N2 Level 39',
    reviewDate: 'Nov 2015',
    price: 'RMB $235/125 grams',
    beanUrl: 'http://www.coffeereview.com/review/nekisse-red-n2-level-39/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Bird Rock Coffee Roasters',
    bean: 'Panama La Esmeralda Bosque Lot 1 Gesha',
    reviewDate: 'Nov 2015',
    price: '$48.00/8 ounces',
    brandUrl: 'http://www.birdrockcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/panama-la-esmeralda-bosque-lot-1-gesha/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 95,
    brand: 'JBC Coffee Roasters',
    bean: 'Finca La Mula Panama Geisha Natural',
    reviewDate: 'Nov 2015',
    price: '$49.95/8 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl:
      'http://www.coffeereview.com/review/finca-la-mula-panama-geisha-natural/',
    location: 'Madison, Wisconsin',
    origin: 'Chiriqui, western Panama.',
    roast: 'Medium-Light',
    agtron: '52/73',
    aroma: '10',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/jbclogo_200x200_72dpi1-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'JBC Coffee Roasters',
    bean: 'La Lagunita El Salvador',
    reviewDate: 'Nov 2015',
    price: '$18.75/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/la-lagunita-el-salvador/',
    location: 'Madison, Wisconsin',
    origin: 'Apaneca, El Salvador',
    roast: 'Medium-Light',
    agtron: '59/79',
    aroma: '9',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/jbclogo_200x200_72dpi1-150x150.jpg',
  },
  {
    rating: 95,
    brand: 'Temple Coffee and Tea',
    bean: 'Kenya Kinuyu AA',
    reviewDate: 'Nov 2015',
    price: '$21.00/12 ounces',
    brandUrl: 'http://www.templecoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-kinuyu-aa/',
    location: 'Sacramento, California',
    origin: 'Kirinyaga District, south-central Kenya',
    roast: 'Medium-Light',
    agtron: '57/70',
    aroma: '10',
    body: '8',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/Marketplace-Temple-new1.jpg',
  },
  {
    rating: 94,
    brand: 'Temple Coffee and Tea',
    bean: 'Costa Rica Alberto Guardia Venecia Honey',
    reviewDate: 'Nov 2015',
    price: '$18.50/12 ounces',
    brandUrl: 'http://www.templecoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/costa-rica-alberto-guardia-venecia-honey/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Dragonfly Coffee Roasters',
    bean: 'Nicaragua Cafe Vidita Los Congos Pacamara Natural',
    reviewDate: 'Nov 2015',
    price: '$18.00/12 ounces',
    brandUrl: 'http://www.dragonflycoffeeroasters.com',
    beanUrl:
      'http://www.coffeereview.com/review/nicaragua-cafe-vidita-los-congos-pacamara-natural/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Barrington Coffee Roasting Co.',
    bean: 'Kenya Kigutha AA',
    reviewDate: 'Nov 2015',
    price: '$17.95/12 ounces',
    brandUrl: 'http://barringtoncoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-kigutha-aa/',
    location: 'Lee, Massachusetts',
    origin: 'Kiambu growing region, south-central Kenya.',
    roast: 'Medium-Light',
    agtron: '60/78',
    aroma: '9',
    body: '8',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/Marketplace-Barrington1.jpg',
  },
  {
    rating: 96,
    brand: 'Klatch Coffee',
    bean: 'Panama Altieri Natural Geisha',
    reviewDate: 'Oct 2015',
    price: '$49.95/8 ounces',
    brandUrl: 'http://www.klatchroasting.com',
    beanUrl:
      'http://www.coffeereview.com/review/panama-altieri-natural-geisha/',
    location: 'Los Angeles, California',
    origin: 'Boquete growing region, western Panama',
    roast: 'Medium',
    agtron: '49/72',
    aroma: '10',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/10/16_375x375-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'Cafe Virtuoso',
    bean: 'Organic Espresso',
    reviewDate: 'Oct 2015',
    price: '$15.00/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/organic-espresso-2/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/10/15_375x375-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'Barrington Coffee Roasting Co.',
    bean: 'Kemgin Ninety Plus',
    reviewDate: 'Oct 2015',
    price: '$25.95/12 ounces',
    brandUrl: 'http://barringtoncoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/kemgin-ninety-plus/',
    location: 'Lee, Massachusetts',
    origin:
      'Wellega, Sidama and Yirgacheffe growing regions, southern and western Ethiopia',
    roast: 'Medium-Light',
    agtron: '52/72',
    aroma: '9',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/Marketplace-Barrington1.jpg',
  },
  {
    rating: 94,
    brand: 'Barrington Coffee Roasting Co.',
    bean: 'Ethiopia Nigusse Lemma',
    reviewDate: 'Oct 2015',
    price: '$16.95/12 ounces',
    brandUrl: 'http://barringtoncoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/ethiopia-nigusse-lemma/',
    location: 'Lee, Massachusetts',
    origin: 'Limu growing region, western Ethiopia',
    roast: 'Medium-Light',
    agtron: '58/76',
    aroma: '9',
    body: '8',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/Marketplace-Barrington1.jpg',
  },
  {
    rating: 96,
    brand: 'Temple Coffee and Tea',
    bean: 'Panama Don Pepe Estate Geisha Single-Origin Espresso',
    reviewDate: 'Oct 2015',
    price: '$19.50/12 ounces',
    brandUrl: 'http://www.templecoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/panama-don-pepe-estate-geisha-single-origin-espresso/',
    location: 'Sacramento, California',
    origin: 'Boquete growing region, western Panama',
    roast: 'Medium',
    agtron: '48/59',
    aroma: '10',
    body: '0',
    withMilk: '10',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/10/6_375x375-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'JBC Coffee Roasters',
    bean: 'Ichamama Kenya',
    reviewDate: 'Oct 2015',
    price: '$16.10/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/ichamama-kenya/',
    location: 'Madison, Wisconsin',
    origin: 'Nyeri County, Central Highlands, Kenya',
    roast: 'Medium-Light',
    agtron: '56/74',
    aroma: '9',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/jbclogo_200x200_72dpi1-150x150.jpg',
  },
  {
    rating: 95,
    brand: 'JBC Coffee Roasters',
    bean: 'Las Flores Espresso',
    reviewDate: 'Oct 2015',
    price: '$15.80/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/las-flores-espresso/',
    location: 'Madison, Wisconsin',
    origin: 'Santa Maria de Dota valley, Tarrazu growing region, Costa Rica',
    roast: 'Medium-Light',
    agtron: '57/78',
    aroma: '9',
    body: '0',
    withMilk: '9',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/10/12_375x375-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'Namusairo Coffee',
    bean: 'El Salvador Finca Medrano Pacamara Nohemi Ventura',
    reviewDate: 'Oct 2015',
    price: 'KRW 40,000/500 grams',
    beanUrl:
      'http://www.coffeereview.com/review/el-salvador-finca-medrano-pacamara-nohemi-ventura/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Crimson Cup Coffee & Tea',
    bean: 'Ethiopia Jimma Agaro',
    reviewDate: 'Oct 2015',
    price: '$20.00/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/ethiopia-jimma-agaro/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 95,
    brand: "Simon Hsieh's Aroma Roast Coffees",
    bean: 'Rwanda Silverback Espresso',
    reviewDate: 'Sep 2015',
    price: 'NT $1,200/16 ounces',
    beanUrl: 'http://www.coffeereview.com/review/rwanda-silverback-espresso/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: "Simon Hsieh's Aroma Roast Coffees",
    bean: 'Ecuador “Mama Kilya” Espresso',
    reviewDate: 'Sep 2015',
    price: 'NT $2,000/16 ounces',
    beanUrl: 'http://www.coffeereview.com/review/ecuador-mama-kilya-espresso/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Lexington Coffee Roasters',
    bean: 'Ethiopia Hambela',
    reviewDate: 'Sep 2015',
    price: '$18.95/12 ounces',
    brandUrl: 'http://www.lexingtoncoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/ethiopia-hambela/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Topeca Coffee Roasters',
    bean: 'Kenya Nyeri Peaberry',
    reviewDate: 'Sep 2015',
    price: '$14.40/12 ounces',
    brandUrl: 'http://topecacoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-nyeri-peaberry/',
    location: 'Tulsa, Oklahoma',
    origin: 'Nyeri County, Central Highlands, Kenya.',
    roast: 'Medium-Light',
    agtron: '55/76',
    aroma: '9',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/09/14_375x375-150x150.jpg',
  },
  {
    rating: 96,
    brand: 'Bird Rock Coffee Roasters',
    bean: 'Panama Lino Esmeralda Geisha Natural',
    reviewDate: 'Sep 2015',
    price: '$51.00/8 ounces',
    brandUrl: 'http://www.birdrockcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/panama-lino-esmeralda-geisha-natural/',
    location: 'La Jolla, California',
    origin: 'Cañas Verdes, Boquete growing region, western Panama.',
    roast: 'Light',
    agtron: '67/88',
    aroma: '9',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/09/18_375x375-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'Illuminista Coffee Roasters',
    bean: 'Ethiopia Sidama Akrabi',
    reviewDate: 'Sep 2015',
    price: '$15.00',
    beanUrl: 'http://www.coffeereview.com/review/ethiopia-sidama-akrabi/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: 'BeanFruit Coffee Co.',
    bean: 'Kenya AA Gakuyuri',
    reviewDate: 'Sep 2015',
    price: '$15.25/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/kenya-aa-gakuyuri/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 95,
    brand: 'Giv COFFEE',
    bean: 'Kenya Embu Gakui Peaberry',
    reviewDate: 'Sep 2015',
    price: '$17.50/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/kenya-embu-gakui-peaberry/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 95,
    brand: "Willoughby's Coffee & Tea",
    bean: 'Kenya AA Kigwandi Estate',
    reviewDate: 'Sep 2015',
    price: '$17.99/16 ounces',
    brandUrl: 'http://www.willoughbyscoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-aa-kigwandi-estate/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Coffee Factorial',
    bean: 'Ethiopia Yirgacheffe Buna Ababa',
    reviewDate: 'Aug 2015',
    price: '$15.00/8 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/ethiopia-yirgacheffe-buna-ababa/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '',
    aroma: '',
    body: '',
    withMilk: '',
    logo: '',
  },
  {
    rating: 96,
    brand: 'Temple Coffee and Tea',
    bean: 'Panama Don Pepe Fully Washed Geisha',
    reviewDate: 'Aug 2015',
    price: '$40.00/8 ounces',
    brandUrl: 'http://www.templecoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/panama-don-pepe-fully-washed-geisha/',
    location: 'Sacramento, California',
    origin: 'Boquete growing region, western Panama.',
    roast: 'Medium-Light',
    agtron: '58/72',
    aroma: '10',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/Marketplace-Temple-new1.jpg',
  },
  {
    rating: 94,
    brand: 'Kean Coffee',
    bean: 'Golden Mean Espresso Blend',
    reviewDate: 'Aug 2015',
    price: '$14.95/12 ounces',
    brandUrl: 'http://www.keancoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/golden-mean-espresso-blend/',
    location: 'Newport Beach, California',
    origin: 'Not disclosed.',
    roast: 'Medium',
    agtron: '48/60',
    aroma: '9',
    body: '0',
    withMilk: '9',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/Marketplace-KeanCoffee1-150x125.jpg',
  },
  {
    rating: 97,
    brand: 'JBC Coffee Roasters',
    bean: 'Finca La Mula Panama Geisha',
    reviewDate: 'Jul 2015',
    price: '$59.95/8 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/finca-la-mula-panama-geisha/',
    location: 'Madison, Wisconsin',
    origin: 'Chiriqui, western Panama.',
    roast: 'Medium',
    agtron: '52/66',
    aroma: '10',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/07/1_375x375-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'Paradise Roasters',
    bean: 'S.O. Espresso Brazil Fazenda Santa Ines',
    reviewDate: 'Jul 2015',
    price: '$12.95/12 ounces',
    brandUrl: 'https://paradiseroasters.com/',
    beanUrl:
      'http://www.coffeereview.com/review/s-o-espresso-brazil-fazenda-santa-ines/',
    location: 'Ramsey, Minnesota',
    origin: 'Carmo de Minas growing region, Minas Gerais State, Brazil.',
    roast: 'Medium',
    agtron: '47/60',
    aroma: '9',
    body: '0',
    withMilk: '9',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/yellow-center-paradise-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'Modern Times',
    bean: 'Black House',
    reviewDate: 'Jul 2015',
    price: '$14.00/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/black-house/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 96,
    brand: 'Klatch Coffee',
    bean: 'Kenya Gachatha AA',
    reviewDate: 'Jun 2015',
    price: '$24.95/12 ounces',
    brandUrl: 'http://www.klatchroasting.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-gachatha-aa/',
    location: 'Los Angeles, California',
    origin: 'Nyeri growing region, south-central Kenya.',
    roast: 'Medium-Light',
    agtron: '54/76',
    aroma: '10',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/06/4_375x375-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'Victrola Coffee Roasters',
    bean: 'Burundi Kayanza Province Mpanga Washing Station',
    reviewDate: 'Jun 2015',
    price: '$21.00/12 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/burundi-kayanza-province-mpanga-washing-station/',
    location: 'Do not have records',
    origin: 'Do not have records',
    roast: 'Do not have records',
    agtron: '0',
    aroma: '',
    body: '',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2015/06/20_375x375-150x150.jpg',
  },
  {
    rating: 94,
    brand: 'Flight Coffee Co.',
    bean: 'Ethiopia Yirgacheffe Dabub Matebya',
    reviewDate: 'Jun 2015',
    price: '$15.00/12 ounces',
    brandUrl: 'http://www.flightcoffeeco.com',
    beanUrl:
      'http://www.coffeereview.com/review/ethiopia-yirgacheffe-dabub-matebya/',
    location: 'Bedford, New Hampshire',
    origin: 'Yirgacheffe growing region, south-central Ethiopia.',
    roast: 'Light',
    agtron: '65/87',
    aroma: '9',
    body: '9',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/Flight_Logo_Square-150x150.jpg',
  },
];
