module.exports = [
  {
    rating: 94,
    brand: 'JBC Coffee Roasters',
    bean: 'ASOPCAFA Colombia',
    reviewDate: 'Dec 2015',
    price: '$14.85/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/asopcafa-colombia/',
    location: 'Madison, Wisconsin',
    origin: 'Huila Department, southern Colombia',
    roast: 'Medium-Light',
    agtron: '60/77',
    aroma: '9',
    body: '8',
    withMilk: '0',
    logo:
      'http://dlo9n43mpvj20faa12i3i3lh.wpengine.netdna-cdn.com/wp-content/uploads/2014/04/jbclogo_200x200_72dpi1-150x150.jpg',
  },
  {
    rating: 95,
    brand: 'Turning Point Coffee',
    bean: 'Guatemala San Sebastian Natural',
    reviewDate: 'Dec 2015',
    price: '$14.50/250 grams',
    brandUrl: 'http://www.turningpointcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/guatemala-san-sebastian-natural/',
    location: 'San Francisco, California',
    origin: 'Antigua Valley, Guatemala',
    roast: 'Medium-Light',
    agtron: '59/78',
    aroma: '9',
    body: '9',
    withMilk: '0',
    logo: '',
  },
  {
    rating: 94,
    brand: 'Turning Point Coffee',
    bean: 'Ethiopia Hachira Natural Espresso',
    reviewDate: 'Dec 2015',
    price: '$22.50/250 grams',
    brandUrl: 'http://www.turningpointcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/ethiopia-hachira-natural-espresso/',
    location: 'San Francisco, California',
    origin: 'Yirgacheffe growing region, southern Ethiopia',
    roast: 'Light',
    agtron: '62/87',
    aroma: '9',
    body: '0',
    withMilk: '9',
    logo: '',
  },
];
