module.exports = [
  {
    rating: 94,
    brand: 'Propeller Coffee',
    bean: 'Ace Espresso',
    reviewDate: 'Nov 2017',
    price: 'CAD $18.00/12 ounces',
    brandUrl: 'http://www.propellercoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/ace-espresso-3/',
    location: 'Toronto, Ontario, Canada',
    origin: 'Mexico; Ethiopia',
    roast: 'Medium-Light',
    agtron: '52/74',
    aroma: '9',
    withMilk: '9',
    notes:
      'Evaluated as espresso. Floral-toned, lively. Black currant, narcissus, sandalwood, roasted cacao nib, molasses in aroma and small cup. Syrupy, buoyant mouthfeel; gently drying, flavor-saturated finish centered around notes of black currant and narcissus. In three parts milk, centered on narcissus-like florals with cocoa tones and black currant just underneath, with hints of sandalwood resurfacing as well.',
  },
  {
    rating: 94,
    brand: 'Propeller Coffee',
    bean: 'Kenya Mutungati',
    reviewDate: 'Nov 2017',
    price: 'CAD $21.00/8 ounces',
    brandUrl: 'http://www.propellercoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-mutungati/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Big Creek Coffee Roasters',
    bean: 'Ethiopia Gedeb Halo Beriti',
    reviewDate: 'Nov 2017',
    price: '$16.50/12 ounces',
    brandUrl: 'http://www.bigcreekcoffeeroasters.com',
    beanUrl: 'http://www.coffeereview.com/review/ethiopia-gedeb-halo-beriti/',
    location: 'Hamilton, Montana',
    origin: 'Gedeb District, Gedeo Zone, southern Ethiopia',
    roast: 'Medium',
    agtron: '48/70',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Deeply sweet, subtly pungent. Honey, pear, tangerine zest, dark chocolate, pistachio in aroma and cup. Sweet and juicy yet crisp in structure (think ripe pear); plush and buoyant in mouthfeel. Resonant and flavor saturated in the short finish; simplifies around hints of tangerine and pistachio in the long.',
  },
  {
    rating: 94,
    brand: 'Reunion Island Coffee',
    bean: 'Ethiopia Sidama',
    reviewDate: 'Nov 2017',
    price: 'CAD $17.00/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/ethiopia-sidama/',
    location: '',
    origin: '',
    roast: '',
    agtron: 'ce: CAD $17.00/12 ounces',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: "PT's Coffee Roasting",
    bean: 'Thiriku AA Kenya',
    reviewDate: 'Nov 2017',
    price: '$24.50/12 ounces',
    brandUrl: 'http://www.ptscoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/thiriku-aa-kenya/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'A.R.C.',
    bean: 'Flora Blend Espresso',
    reviewDate: 'Nov 2017',
    price: 'HKD $158/227 grams',
    beanUrl: 'http://www.coffeereview.com/review/flora-blend-espresso/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'A.R.C.',
    bean: '“Sweety” Espresso Blend',
    reviewDate: 'Nov 2017',
    price: 'HKD $250/227 grams',
    beanUrl: 'http://www.coffeereview.com/review/sweety-espresso-blend/',
    location: '',
    origin: '',
    roast: '',
    agtron: 'ce: HKD $250/227 grams',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'A.R.C.',
    bean: '“Fruity” Espresso Blend',
    reviewDate: 'Nov 2017',
    price: 'HKD $200/227 grams',
    beanUrl: 'http://www.coffeereview.com/review/fruity-espresso-blend/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'JBC Coffee Roasters',
    bean: 'El Aquila Pacamara Espresso',
    reviewDate: 'Oct 2017',
    price: '$17.90/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/el-aquila-pacamara-espresso/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Bird Rock Coffee Roasters',
    bean: 'Guatemala Finca El Injerto Gesha',
    reviewDate: 'Oct 2017',
    price: '$51.00/8 ounces',
    brandUrl: 'http://www.birdrockcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/guatemala-finca-el-injerto-gesha/',
    location: 'San Diego, California',
    origin: 'Huehuetenango Department, Guatemala',
    roast: 'Medium-Light',
    agtron: '56/82',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Delicate and confident, sweetly spice-toned. Dried coconut, frankincense, baker’s chocolate, tea rose, tamarind in aroma and cup. Sweetly savory and balanced in structure; buoyant, silky-smooth mouthfeel. The finish leads with notes of chocolate and frankincense in the short, lifting to sweet-tart tamarind and coconut in the long.',
  },
  {
    rating: 94,
    brand: 'Dragonfly Coffee Roasters',
    bean: 'Kenya Gatomboya AA',
    reviewDate: 'Oct 2017',
    price: '$18.00/12 ounces',
    brandUrl: 'http://www.dragonflycoffeeroasters.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-gatomboya-aa-2/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Red Rooster Coffee Roaster',
    bean: 'Flight Seasonal Espresso',
    reviewDate: 'Oct 2017',
    price: '$16.49/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/flight-seasonal-espresso-4/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Ho Soo Tsai',
    bean: 'A.G.E. Duetto Espresso',
    reviewDate: 'Oct 2017',
    price: '$26.00/8 ounces',
    beanUrl: 'http://www.coffeereview.com/review/g-e-duetto-espresso/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Greater Goods Coffee Roasters',
    bean: 'Kenya Nyeri Hill Farm',
    reviewDate: 'Oct 2017',
    price: '$18.00/12 ounces',
    brandUrl: 'http://greatergoodsroasting.com/',
    beanUrl: 'http://www.coffeereview.com/review/kenya-nyeri-hill-farm-2/',
    location: 'Austin, Texas',
    origin: 'Nyeri growing region, south-central Kenya',
    roast: 'Medium-Light',
    agtron: '55/79',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Balanced, richly sweet, spice-toned. Apricot, baker’s chocolate, lilac, coriander, fresh-cut cedar in aroma and cup. Deep, sweet-savory structure with bright acidity; crisp, satiny mouthfeel. The finish is paradoxically dry yet juicy, leading with resonant notes of apricot and fresh-ground coriander in the short and cocoa-toned sweet florals in the long.',
  },
  {
    rating: 94,
    brand: 'Paradise Roasters',
    bean: 'Jinotega Geisha',
    reviewDate: 'Oct 2017',
    price: '$18.95/12 ounces',
    brandUrl: 'https://paradiseroasters.com/',
    beanUrl: 'http://www.coffeereview.com/review/jinotega-geisha/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Giv COFFEE',
    bean: 'Nicaragua Un Regalo de Dios Bourbon',
    reviewDate: 'Oct 2017',
    price: '$16.99/12 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/nicaragua-un-regalo-de-dios-bourbon/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'JBC Coffee Roasters',
    bean: 'Gedeb Lot 83 Ethiopia Natural',
    reviewDate: 'Sep 2017',
    price: '$18.95/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl:
      'http://www.coffeereview.com/review/gedeb-lot-83-ethiopia-natural/',
    location: 'Madison, Wisconsin',
    origin: 'Gedeb District, Gedeo Zone, southern Ethiopia',
    roast: 'Medium-Light',
    agtron: '58/82',
    aroma: '9',
    acidity: ' 9',
    notes:
      'High-toned, crisply sweet-tart, richly savory. Jasmine, roasted cacao nib, lemon verbena, grapefruit zest, aromatic mushroom in aroma and cup. Balanced sweetly tart structure with a rich umami undercurrent; buoyant, satiny mouthfeel. The flavor-saturated finish leads with floral notes (jasmine) and closes with crisply sweet citrus  (lemon verbena, grapefruit zest).',
  },
  {
    rating: 94,
    brand: 'JBC Coffee Roasters',
    bean: 'Halo Beriti Ethiopia',
    reviewDate: 'Sep 2017',
    price: '$17.90/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/halo-beriti-ethiopia/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Red Rooster Coffee Roaster',
    bean: 'Ethiopia Konga Sede',
    reviewDate: 'Sep 2017',
    price: '$16.49/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/ethiopia-konga-sede/',
    location: '',
    origin: '',
    roast: '',
    agtron: 'ce: $16.49/12 ounces',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Espresso Republic',
    bean: 'Static Amaro Gayo Natural Ethiopia',
    reviewDate: 'Sep 2017',
    price: '$17.00/12 ounces',
    brandUrl: 'http://www.espressorepublic.com',
    beanUrl:
      'http://www.coffeereview.com/review/static-amaro-gayo-natural-ethiopia/',
    location: 'Chino, California',
    origin: 'Yirgacheffe growing region, southern Ethiopia',
    roast: 'Medium',
    agtron: '45/61',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Crisply sweet, fruit-forward. Ripe strawberry, aromatic orchid, honey, toasted pine nut, a hint of sumac spice in aroma and cup. Lavish, elegant structure, with sweet-tart-savory in harmonious balance. Syrupy mouthfeel. The finish is resonant, long and flavor-saturated, maintaining the promise of the complex flavor notes from the cup.',
  },
  {
    rating: 94,
    brand: 'Espresso Republic',
    bean: 'Static Cali Classic Espresso',
    reviewDate: 'Sep 2017',
    price: '$14.95/12 ounces',
    brandUrl: 'http://www.espressorepublic.com',
    beanUrl:
      'http://www.coffeereview.com/review/static-cali-classico-espresso/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Seeker Co, Ltd.',
    bean: 'Shine Day El Salvador',
    reviewDate: 'Sep 2017',
    price: 'NT $490/225 grams',
    beanUrl: 'http://www.coffeereview.com/review/shine-day-el-salvador/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Kakalove Cafe',
    bean: 'Kenya Kirinyaga Baragwi Guama AB',
    reviewDate: 'Sep 2017',
    price: 'NT $600/16 ounces',
    brandUrl: 'http://www.kakalovecafe.com.tw/',
    beanUrl:
      'http://www.coffeereview.com/review/kenya-kirinyaga-baragwi-guama-ab/',
    location: 'Chia-Yi, Taiwan',
    origin: 'Kirinyaga District, south-central Kenya',
    roast: 'Medium-Light',
    agtron: '59/77',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Delicately bright, deeply sweet. Red currant, roasted macadamia, myrrh, honey, dried hibiscus in aroma and cup. Balanced, high-toned, sweetly tart in structure; silky, buoyant mouthfeel. The finish is long, flavor-laden and confident, leading with notes of red fruit and tart florals in the short, followed by suggestions of honey-toned nut (think creamy macadamia) and elegantly musky myrrh.',
  },
  {
    rating: 94,
    brand: 'Kakalove Cafe',
    bean: 'Guatemala Finca El General Espresso',
    reviewDate: 'Sep 2017',
    price: 'NT $550/16 ounces',
    brandUrl: 'http://www.kakalovecafe.com.tw/',
    beanUrl:
      'http://www.coffeereview.com/review/guatemala-finca-el-general-espresso/',
    location: 'Chia-Yi, Taiwan',
    origin: 'Acatenango growing region, central Guatemala',
    roast: 'Medium-Light',
    agtron: '56/76',
    aroma: '9',
    withMilk: '9',
    notes:
      'Evaluated as espresso. Fruit-toned, sweetly tart. Raspberry jam, almond, dark chocolate, narcissus, sandalwood in aroma and small cup. Plush, syrupy mouthfeel. The crisp, chocolate-toned finish is complicated by complex, jammy notes of raspberry in the short, consolidating to dark chocolate and sandalwood in the long. In three parts milk, fruit and chocolate deepen and round.',
  },
  {
    rating: 94,
    brand: 'Topeca Coffee Roasters',
    bean: 'Kenya Boma Peaberry',
    reviewDate: 'Sep 2017',
    price: '$16.99/12 ounces',
    brandUrl: 'http://topecacoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-boma-peaberry/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Coffee Dusk Roasters',
    bean: 'Ethiopia Guji Zone Natural',
    reviewDate: 'Sep 2017',
    price: 'KRW $13,000/200 grams',
    beanUrl: 'http://www.coffeereview.com/review/ethiopia-guji-zone-natural/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Topeca Coffee Roasters',
    bean: 'Kenya Boma AA',
    reviewDate: 'Sep 2017',
    price: '$15.99/12 ounces',
    brandUrl: 'http://topecacoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-boma-aa/',
    location: 'Tulsa, Oklahoma',
    origin: 'Baringo and Nakura Counties, central Kenya',
    roast: 'Medium-Light',
    agtron: '53/76',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Sweetly delicate yet deeply pungent: fragrant, intricate. Red clover honey, black currant, dark chocolate, fresh-cut pine, violet-like flowers in aroma and cup. Richly and roundly sweet-tart in structure; velvety yet lively and light-footed in mouthfeel. Flowers in particular carry into a long, deeply flavor-saturated finish.',
  },
  {
    rating: 94,
    brand: 'Durango Coffee Company',
    bean: 'Colombia Finca Campoalegre',
    reviewDate: 'Sep 2017',
    price: '$12.95/12 ounces',
    brandUrl: 'http://www.durangocoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/colombia-finca-campoalegre/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'San Francisco Bay Coffee',
    bean: 'Panama Geisha',
    reviewDate: 'Sep 2017',
    price: '$29.99/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/panama-geisha-2/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Dragonfly Coffee Roasters',
    bean: 'Esmeralda Special Auction Washed Geisha',
    reviewDate: 'Sep 2017',
    price: '$50.00/8 ounces',
    brandUrl: 'http://www.dragonflycoffeeroasters.com',
    beanUrl:
      'http://www.coffeereview.com/review/esmeralda-special-auction-washed-geisha/',
    location: 'Boulder, Colorado',
    origin: 'Boquete growing region, western Panama',
    roast: 'Medium-Light',
    agtron: '54/78',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Delicately rich, deeply sweet, lushly intricate. Complex flowers (rose, lavender) apple, tangerine zest, roasted almond, baker’s chocolate in aroma and cup. Deeply sweet in structure, with a pleasantly brisk, bitterish complication. Crisply smooth, satiny mouthfeel. Apple, almond, lavender in particular carry into a very sweet finish.',
  },
  {
    rating: 95,
    brand: 'Mudhouse Coffee Roasters',
    bean: 'Gesha Village 1931, Lot 86',
    reviewDate: 'Sep 2017',
    price: '$75.00/8 ounces',
    beanUrl: 'http://www.coffeereview.com/review/gesha-village-1931-lot-86/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Kakalove Cafe',
    bean: 'Gesha Village Natural Oma Block Lot 72',
    reviewDate: 'Sep 2017',
    price: 'NT $3200/16 ounces',
    brandUrl: 'http://www.kakalovecafe.com.tw/',
    beanUrl:
      'http://www.coffeereview.com/review/gesha-village-natural-oma-black/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Ho Soo Tsai',
    bean: 'Gesha Village Lot 76 Nasha Block',
    reviewDate: 'Sep 2017',
    price: '$37.00/4 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/gesha-village-lot-76-natural-nasha-block/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Hatch Coffee',
    bean: 'Gesha Village Auction Lot 26 Gori Gesha Natural',
    reviewDate: 'Sep 2017',
    price: 'CAD $30.00/100 grams',
    beanUrl:
      'http://www.coffeereview.com/review/gesha-village-auction-lot-26-gori-gesha-natural/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 96,
    brand: 'Dragonfly Coffee Roasters',
    bean: 'Carmen Geisha El Palomar Best of Panama #4 Carlos Aguilera',
    reviewDate: 'Sep 2017',
    price: '$50.00/8 ounces',
    brandUrl: 'http://www.dragonflycoffeeroasters.com',
    beanUrl:
      'http://www.coffeereview.com/review/carmen-geisha-el-palomar-best-of-panama-4-carlos-aguilera/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'JBC Coffee Roasters',
    bean: 'Karuthi Espresso',
    reviewDate: 'Aug 2017',
    price: '$18.95/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/karuthi-espresso/',
    location: 'Madison, Wisconsin',
    origin: 'Nyeri growing region, south-central Kenya',
    roast: 'Medium-Light',
    agtron: '53/77',
    aroma: '9',
    withMilk: '9',
    notes:
      'Evaluated as espresso. High-toned, floral-savory. Wisteria, nut-toned chocolate, maraschino cherry, fresh-cut cedar, grapefruit zest in aroma and small cup. Lush, syrupy body. The sweetly crisp, tart finish is assertive and maintains all of the notes from the cup. In three parts milk, wisteria notes are elevated, supported by nut-toned chocolate suggestions.',
  },
  {
    rating: 94,
    brand: 'JBC Coffee Roasters',
    bean: 'Chelelektu Espresso',
    reviewDate: 'Aug 2017',
    price: '$17.25/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/chelelektu-espresso/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'JBC Coffee Roasters',
    bean: 'Karuthi Kenya',
    reviewDate: 'Aug 2017',
    price: '$18.95/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/karuthi-kenya/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Amavida Coffee and Tea',
    bean: 'Finca El Obraje Colombia Gesha',
    reviewDate: 'Aug 2017',
    price: '$29.95/6 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/finca-el-obraje-colombia-gesha/',
    location: '',
    origin: '',
    roast: '',
    agtron: '',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Another Beans Coffee Roasters',
    bean: 'Kenya AA Top Nyeri Tekangu Tegu Microlot',
    reviewDate: 'Aug 2017',
    price: 'KRW 19,000/200 grams',
    beanUrl:
      'http://www.coffeereview.com/review/kenya-aa-top-nyeri-tekangu-tegu-microlot/',
    location: '',
    origin: '',
    roast: '',
    agtron: 'ce: KRW 19,000/200 grams',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Greenstone Coffee',
    bean: 'Washed Ethiopia Yirgacheffe Banko Gotiti',
    reviewDate: 'Aug 2017',
    price: 'NT $550/8 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/washed-ethiopia-yirgacheffe-banko-gotiti/',
    location: '',
    origin: '',
    roast: '',
    agtron: 'ce: NT $550/8 ounces',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Paradise Roasters',
    bean: 'Sumatra Danau Toba',
    reviewDate: 'Aug 2017',
    price: '$16.95/12 ounces',
    brandUrl: 'https://paradiseroasters.com/',
    beanUrl: 'http://www.coffeereview.com/review/sumatra-danau-toba-4/',
    location: 'Ramsey, Minnesota',
    origin:
      'Lintong growing region, North Sumatra Province, Sumatra, Indonesia',
    roast: 'Medium-Light',
    agtron: '55/77',
    aroma: '9',
    acidity: ' 8',
    notes:
      'Deeply and richly sweet, wood-framed. Geranium, cedar, chocolate fudge, ripe banana, perique (fermented) pipe tobacco in aroma and cup. Gentle, crisp acidity; viscous, satiny mouthfeel. The long, resonant finish is centered around notes of deep chocolate and pipe tobacco, lifted by suggestions of ripe tropical fruit.',
  },
  {
    rating: 94,
    brand: 'Lexington Coffee Roasters',
    bean: 'Kapsakiso Kenya',
    reviewDate: 'Aug 2017',
    price: '$18.95/12 ounces',
    brandUrl: 'http://www.lexingtoncoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/kapsakiso-kenya/',
    location: 'Lexington, Virginia',
    origin: 'Bungoma region, western Kenya',
    roast: 'Light',
    agtron: '60/84',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Deeply rich, crisply sweet-savory. Graham cracker, violet, black currant, blood-orange zest, raw chocolate in aroma and cup. Zesty, well-integrated acidity; syrupy-smooth mouthfeel. The quietly elegant finish leads with soft florals in the short that build and deepen to black currant and chocolate in the long.',
  },
  {
    rating: 95,
    brand: 'Kakalove Cafe',
    bean: 'Ethiopia Washed Kayon Mountain',
    reviewDate: 'Aug 2017',
    price: 'NT $550/16 ounces',
    brandUrl: 'http://www.kakalovecafe.com.tw/',
    beanUrl:
      'http://www.coffeereview.com/review/ethiopia-washed-kayon-mountain/',
    location: 'Chia-Yi, Taiwan',
    origin: 'Odo Shakiso District, Guji Zone, southern Ethiopia',
    roast: 'Medium-Light',
    agtron: '58/80',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Floral-toned, chocolaty. Fine musk, strawberry guava, dark chocolate, honey, oak in aroma and cup. Juicy, savory-tart acidity; syrupy-smooth mouthfeel. All the notes from the cup carry into a finish both flavor-laden and long.',
  },
  {
    rating: 97,
    brand: 'JBC Coffee Roasters',
    bean: 'Ninety Plus Gesha Estates Limited Batch #227',
    reviewDate: 'Jul 2017',
    price: '$68.50/4 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl:
      'http://www.coffeereview.com/review/ninety-plus-gesha-estates-limited-batch-227/',
    location: 'Madison, Wisconsin',
    origin: 'Chiriqui Province, far western Panama',
    roast: 'Light',
    agtron: '67/97',
    aroma: '10',
    acidity: ' 9',
    notes:
      'Delicate yet deeply aromatic, gloriously and almost impossibly complex in its fruit and floral expression. Fruit ranges from grapefruit through lychee to passionfruit; flowers suggest lavender, rose, more. There is chocolate and a grapy Cognac reduction, and finally a savory resonance we called sweet mushroom. Juicy, floral-tart acidity; viscous, syrupy mouthfeel. The finish is laden with complex floral top-notes in the short, rounding to hints of sweet fruit and deep Cognac-toned chocolate in the long.',
  },
  {
    rating: 95,
    brand: 'JBC Coffee Roasters',
    bean: 'Tano Batak Sumatra',
    reviewDate: 'Jul 2017',
    price: '$16.50/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/tano-batak-sumatra-4/',
    location: 'Madison, Wisconsin',
    origin:
      'Lintong growing region, North Sumatra Province, Sumatra, Indonesia',
    roast: 'Medium-Light',
    agtron: '54/80',
    aroma: '10',
    acidity: ' 9',
    notes:
      'Richly sweet, intricately layered. Lychee, chocolate fudge, bay leaf, pipe tobacco, aromatic orchid, a hint of fresh-turned earth in aroma and cup. Juicy, sweet-tart acidity; plush, syrupy mouthfeel. Notes of cocoa and sweet pipe tobacco resonate in the crisp, dry finish.',
  },
  {
    rating: 94,
    brand: 'Big Shoulders Coffee',
    bean: 'Makwa Kenya AB',
    reviewDate: 'Jul 2017',
    price: '$14.00/12 ounces',
    brandUrl: 'http://www.bigshoulderscoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/makwa-kenya-ab/',
    location: 'Chicago, Illinois',
    origin: 'Nyeri growing region, south-central Kenya',
    roast: 'Light',
    agtron: '62/84',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Richly pungent, sweet-savory. Coconut, violet, baker’s chocolate, musky hops, oak in aroma and cup. Vibrant, sweet acidity; delicate, velvety-smooth mouthfeel. The sweet-toned finish consolidates to floral and chocolate notes enveloped in a savory edge that suggests hops. ',
  },
  {
    rating: 94,
    brand: 'Topeca Coffee Roasters',
    bean: 'Finca El Guamo Colombia',
    reviewDate: 'Jun 2017',
    price: '$15.99/12 ounces',
    brandUrl: 'http://topecacoffee.com',
    beanUrl: 'http://www.coffeereview.com/review/finca-el-guamo-colombia/',
    location: 'Tulsa, Oklahoma',
    origin: 'Gaitania, Tolima Department, central Colombia',
    roast: 'Medium-Light',
    agtron: '54/75',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Deeply and richly sweet; floral-toned. Lilac, roasted cacao nib, cardamom, myrrh, mango in aroma and cup. Bright, juicy acidity; delicate, silky mouthfeel. The crisp, richly drying finish leads with notes of lilac in the short, consolidating to cacao nib and apricot in the long.',
  },
  {
    rating: 94,
    brand: 'Dragonfly Coffee Roasters',
    bean: 'Kenya Ndaroini AA',
    reviewDate: 'Jun 2017',
    price: '$20.00/12 ounces',
    brandUrl: 'http://www.dragonflycoffeeroasters.com',
    beanUrl: 'http://www.coffeereview.com/review/kenya-ndaroini-aa/',
    location: 'Boulder, Colorado',
    origin: 'Nyeri growing region, south-central Kenya',
    roast: 'Medium-Light',
    agtron: '54/76',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Complex, deeply and richly sweet. Dried coconut, dark chocolate, cherry blossom, tamarind, molasses in aroma and cup. Juicy, balanced, sweetly savory acidity; delicate, velvety mouthfeel. The resonant finish is deeply layered, leading with notes of cherry blossom and molasses in the short, followed by tart tamarind-like fruit notes, rounding to dark chocolate and a hint of coconut in the long.',
  },
  {
    rating: 94,
    brand: 'Bird Rock Coffee Roasters',
    bean: 'El Salvador Finca Kilimanjaro Natural',
    reviewDate: 'Jun 2017',
    price: '$35.00/12 ounces',
    brandUrl: 'http://www.birdrockcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/el-salvador-finca-kilimanjaro-natural/',
    location: 'San Diego, California',
    origin: 'Santa Ana Department, El Salvador',
    roast: 'Medium-Light',
    agtron: '54/78',
    aroma: '9',
    acidity: ' 8',
    notes:
      'Sweetly tart, floral-toned. Lavender, passionfruit, roasted cacao nib, almond brittle, allspice in aroma and cup. Crisply sweet acidity; full, syrupy mouthfeel. The flavor-saturated finish is deep with cocoa- and spice-toned floral notes in the resonant short and perhaps a hint of sweet, grappa-like ferment in the long.',
  },
  {
    rating: 96,
    brand: 'JBC Coffee Roasters',
    bean: 'Kamagogo Kenya',
    reviewDate: 'Jun 2017',
    price: '$20.90/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/kamagogo-kenya/',
    location: 'Madison, Wisconsin',
    origin: 'Murang’a Foothills, Aberdare Ridge, Central Province, Kenya',
    roast: 'Medium-Light',
    agtron: '53/76',
    aroma: '9',
    acidity: ' 9',
    notes:
      'An exquisite Kenya: bold, richly sweet-savory, and deeply inviting.',
  },
  {
    rating: 94,
    brand: 'JBC Coffee Roasters',
    bean: 'Twisted 4.0 Espresso',
    reviewDate: 'Jun 2017',
    price: '$15.75/12 ounces',
    brandUrl: 'https://www.jbccoffeeroasters.com/90-plus-coffees',
    beanUrl: 'http://www.coffeereview.com/review/twisted-4-0-espresso/',
    location: 'Madison, Wisconsin',
    origin: 'Not disclosed',
    roast: 'Medium-Light',
    agtron: '53/75',
    aroma: '9',
    withMilk: '9',
    notes:
      'Evaluated as espresso. Deeply and richly sweet-tart. Dark chocolate, hazelnut, black cherry, lavender, sandalwood in aroma and small cup. Delicate, silky mouthfeel; sweet, chocolate-toned finish with supporting notes of lavender and sandalwood. In three parts milk, pungent floral tones are elevated and sweet cocoa notes deepen.',
  },
  {
    rating: 95,
    brand: "PT's Coffee Roasting",
    bean: 'El Salvador Finca Kilimanjaro Cascara Fermentation Aida Batlle',
    reviewDate: 'Jun 2017',
    price: '$35.00/12 ounces',
    brandUrl: 'http://www.ptscoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/el-salvador-finca-kilimanjaro-cascara-fermentation-aida-batlle/',
    location: 'Topeka, Kansas',
    origin: 'Santa Ana Department, El Salvador',
    roast: 'Medium',
    agtron: '50/71',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Intensely sweet, intricate. Dark chocolate, aromatic orchid, strawberry guava, almond butter, frankincense in aroma and cup. Juicy, savory-sweet acidity; delicate, satiny mouthfeel. A bonus coconut note surfaces in the resonant, flavor-saturated finish.',
  },
  {
    rating: 94,
    brand: 'Big Island Coffee Roasters',
    bean: 'Puna Natural',
    reviewDate: 'Jun 2017',
    price: '$29.00/10 ounces',
    brandUrl: 'http://www.bigislandcoffeeroasters.com',
    beanUrl: 'http://www.coffeereview.com/review/puna-natural/',
    location: 'Mountain View, Hawaii',
    origin: 'Puna District, Big Island of Hawaii',
    roast: 'Medium-Light',
    agtron: '54/74',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Abundantly sweet, deeply rich and savory. Dried apricot, lime zest, nougat, lavender, thyme in aroma and cup. Round, fruit-toned acidity; lightly syrupy mouthfeel. The resonant finish is characterized by savory herb notes, nougat and hints of piquant citrus zest.',
  },
  {
    rating: 94,
    brand: 'Bird Rock Coffee Roasters',
    bean: 'Colombia La Palma Y El Tucan Gesha',
    reviewDate: 'Jun 2017',
    price: 'NA',
    brandUrl: 'http://www.birdrockcoffee.com',
    beanUrl:
      'http://www.coffeereview.com/review/colombia-la-palma-y-el-tucan-gesha/',
    location: 'San Diego, California',
    origin: 'Cundinamarca Department, central Colombia',
    roast: 'Light',
    agtron: '62/84',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Exuberant, delicately spice-toned. Sandalwood, roasted cacao nib, strawberry, roasted almond, tea rose in aroma and cup. Bright, juicy, intensely floral-toned acidity; velvety mouthfeel. The flavorful finish leads with notes of cacao nib and strawberry in the short, consolidating to sandalwood and rose in an impressively ringing, persistent long.',
  },
  {
    rating: 94,
    brand: 'Hula Daddy Kona Coffee',
    bean: 'Bourbon Peaberry',
    reviewDate: 'May 2017',
    price: '$49.95/8 ounces',
    brandUrl: 'http://www.huladaddy.com',
    beanUrl: 'http://www.coffeereview.com/review/bourbon-peaberry/',
    location: 'Holulaloa, Hawaii',
    origin: 'Holualoa, North Kona growing district, “Big Island” of Hawaii',
    roast: 'Medium-Light',
    agtron: '54/80',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Richly sweet, deeply savory. Lime zest, white peppercorn, milk chocolate, sandalwood, dried coconut in aroma and cup. Lively, lyrical acidity; full, syrupy mouthfeel. The flavor-saturated finish is laden with all the notes promised by both aroma and flavor, though the lime zest softens to lime blossom as the finish lengthens and turns resonantly floral. ',
  },
  {
    rating: 94,
    brand: 'Notch Coffee',
    bean: 'Sumatra Boru Batak',
    reviewDate: 'May 2017',
    price: '$14.99/12 ounces',
    beanUrl: 'http://www.coffeereview.com/review/sumatra-boru-batak/',
    location: '',
    origin: '',
    roast: '',
    agtron: 'ce: $14.99/12 ounces',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 95,
    brand: 'Dragonfly Coffee Roasters',
    bean: 'Gesha Village Estate Bench Maji Gesha G1',
    reviewDate: 'May 2017',
    price: '$35.00/8 ounces',
    brandUrl: 'http://www.dragonflycoffeeroasters.com',
    beanUrl:
      'http://www.coffeereview.com/review/gesha-village-estate-bench-maji-gesha-g1/',
    location: 'Boulder, Colorado',
    origin: 'Bench-Maji Zone, Southern Ethiopia',
    roast: 'Medium-Light',
    agtron: '55/78',
    aroma: '9',
    acidity: ' 9',
    notes:
      'Delicate, intensely sweet, floral-toned. Star jasmine, tangerine, roasted cacao nib, maple syrup, myrrh in aroma and cup. Lively, sweet-tart acidity; plush, satiny mouthfeel. The resonant finish carries through on the promise of the aroma with deep floral and bright citrus tones, both grounded by hints of cocoa.',
  },
  {
    rating: 94,
    brand: 'Modern Times Coffee',
    bean: 'Bourbon-Barrel-Aged Kenya Baragu',
    reviewDate: 'May 2017',
    price: '$20.00/8 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/bourbon-barrel-aged-kenya-baragu/',
    location: '',
    origin: '',
    roast: '',
    agtron: 'ce: $20.00/8 ounces',
    aroma: '',
    acidity: '',
    notes: '',
  },
  {
    rating: 94,
    brand: 'Equator Coffees & Teas',
    bean: 'Aged Sumatra Ulos Batak Peaberry',
    reviewDate: 'May 2017',
    price: '$18.00/12 ounces',
    beanUrl:
      'http://www.coffeereview.com/review/aged-sumatra-ulos-batak-peaberry/',
    location: '',
    origin: '',
    roast: '',
    agtron: 'ce: $18.00/12 ounces',
    aroma: '',
    acidity: '',
    notes: '',
  },
];
